"""empty message

Revision ID: 0c8e513a0584
Revises: 989d5d742b60
Create Date: 2018-01-07 15:11:44.008637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8e513a0584'
down_revision = '989d5d742b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('up', sa.Boolean(), server_default=sa.sql.expression.literal(False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('up')

    # ### end Alembic commands ###
