"""empty message

Revision ID: bd998a2e5123
Revises: 4119132487e2
Create Date: 2017-11-13 05:15:16.414991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd998a2e5123'
down_revision = '4119132487e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('important', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'important')
    # ### end Alembic commands ###
