"""empty message

Revision ID: d43eb7d939f4
Revises: 
Create Date: 2017-11-05 16:00:00.409349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43eb7d939f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('macaddress', sa.String(length=255), nullable=False),
    sa.Column('ipaddress', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('lastseen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('macaddress'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('ipaddress'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('vendor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
